services:
  warp:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    ports:
      - "2080-2124:2080-2124"
      - "9090:9090"

    environment:
      WARP_INSTANCES: "${WARP_INSTANCES:-20}"

      PROXY_MODE: "dedicated"
      PROXY_BASE_PORT: "2080"

      PROXY_MAX_CONN: "200"
      PROXY_MAX_RPS: "50"

      WARP_CONNECT_TIMEOUT: "90"

      ADMIN_ENABLED: "true"
      ADMIN_PORT: "9090"
      ADMIN_USER: "${ADMIN_USER}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

      PROXY_HOST_OMNIROUTE: "${PROXY_HOST_OMNIROUTE:-omniroute_warp-proxy}"

    volumes:
      - warp-data:/var/lib/cloudflare-warp

    networks:
      default:
      dokploy-network:
        aliases:
          - omniroute_warp-proxy
          - omniroute_warp-proxy_undefined

volumes:
  warp-data:

networks:
  dokploy-network:
    external: true
    name: dokploy-network